services:

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped

    ports:
      - "8554:8554"

    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro


  fake-cameras:
    image: jrottenberg/ffmpeg:7.1-ubuntu
    container_name: fake-cameras
    restart: unless-stopped

    depends_on:
      - mediamtx

    volumes:
      - ./videos:/videos:ro
      - ./scripts/start-streams.sh:/start-streams.sh:ro

    entrypoint:
      - /bin/bash
      - /start-streams.sh
